"""https://slurm.schedmd.com/rest_api.html#v0.0.42_job_info"""

from typing import Optional

from pydantic import BaseModel

from .float64_no_val_struct import Float64NoValStruct
from .job_info_power import JobInfoPower
from .job_res import JobRes
from .part_prio import PartPrio
from .process_exit_code_verbose import ProcessExitCodeVerbose
from .uint16_no_val_struct import Uint16NoValStruct
from .uint32_no_val_struct import Uint32NoValStruct
from .uint64_no_val_struct import Uint64NoValStruct


class JobInfo(BaseModel):
    """v0.0.42 JOB_INFO"""

    account: Optional[str]
    accrue_time: Optional[Uint64NoValStruct]
    admin_comment: Optional[str]
    allocating_node: Optional[str]
    array_job_id: Optional[Uint32NoValStruct]
    array_task_id: Optional[Uint32NoValStruct]
    array_max_tasks: Optional[Uint32NoValStruct]
    array_task_string: Optional[str]
    association_id: Optional[int]
    batch_features: Optional[str]
    batch_flag: Optional[bool]
    batch_host: Optional[str]
    flags: Optional[list[str]]
    burst_buffer: Optional[str]
    burst_buffer_state: Optional[str]
    cluster: Optional[str]
    cluster_features: Optional[str]
    command: Optional[str]
    comment: Optional[str]
    container: Optional[str]
    container_id: Optional[str]
    contiguous: Optional[bool]
    core_spec: Optional[int]
    thread_spec: Optional[int]
    cores_per_socket: Optional[Uint16NoValStruct]
    billable_tres: Optional[Float64NoValStruct]
    cpus_per_task: Optional[Uint16NoValStruct]
    cpu_frequency_mininum: Optional[Uint32NoValStruct]
    cpu_frequency_maximum: Optional[Uint32NoValStruct]
    cpu_frequency_governor: Optional[Uint32NoValStruct]
    cpus_per_tres: Optional[str]
    cron: Optional[str]
    deadline: Optional[Uint64NoValStruct]
    delay_boot: Optional[Uint32NoValStruct]
    dependency: Optional[str]
    derived_exit_code: Optional[ProcessExitCodeVerbose]
    eligible_time: Optional[Uint64NoValStruct]
    end_time: Optional[Uint64NoValStruct]
    excluded_nodes: Optional[str]
    exit_code: Optional[ProcessExitCodeVerbose]
    extra: Optional[str]
    failed_node: Optional[str]
    features: Optional[str]
    federation_origin: Optional[str]
    federation_siblings_active: Optional[str]
    federation_siblings_viable: Optional[str]
    gres_detail: Optional[list[str]]
    group_id: Optional[int]
    group_name: Optional[str]
    het_job_id: Optional[Uint32NoValStruct]
    het_job_id_set: Optional[str]
    het_job_offset: Optional[Uint32NoValStruct]
    job_id: Optional[int]
    job_resources: Optional[JobRes]
    job_size_str: Optional[list[str]]
    job_state: Optional[list[str]]
    last_sched_evaluation: Optional[Uint64NoValStruct]
    licenses: Optional[str]
    mail_type: Optional[list[str]]
    mail_user: Optional[str]
    max_cpus: Optional[Uint32NoValStruct]
    max_nodes: Optional[Uint32NoValStruct]
    mcs_label: Optional[str]
    memory_per_tres: Optional[str]
    name: Optional[str]
    network: Optional[str]
    nodes: Optional[str]
    nice: Optional[int]
    tasks_per_core: Optional[Uint16NoValStruct]
    tasks_per_tres: Optional[Uint16NoValStruct]
    tasks_per_node: Optional[Uint16NoValStruct]
    tasks_per_socket: Optional[Uint16NoValStruct]
    tasks_per_board: Optional[Uint16NoValStruct]
    cpus: Optional[Uint32NoValStruct]
    node_count: Optional[Uint32NoValStruct]
    tasks: Optional[Uint32NoValStruct]
    partition: Optional[str]
    prefer: Optional[str]
    memory_per_cpu: Optional[Uint64NoValStruct]
    memory_per_node: Optional[Uint64NoValStruct]
    minimum_cpus_per_node: Optional[Uint16NoValStruct]
    minimum_tmp_disk_per_node: Optional[Uint32NoValStruct]
    power: Optional[JobInfoPower]
    preempt_time: Optional[Uint64NoValStruct]
    preemptable_time: Optional[Uint64NoValStruct]
    pre_sus_time: Optional[Uint64NoValStruct]
    hold: Optional[bool]
    priority: Optional[Uint32NoValStruct]
    priority_by_partition: Optional[PartPrio]
    profile: Optional[list[str]]
    qos: Optional[str]
    reboot: Optional[bool]
    required_nodes: Optional[str]
    required_switches: Optional[int]
    requeue: Optional[bool]
    resize_time: Optional[Uint64NoValStruct]
    restart_cnt: Optional[int]
    resv_name: Optional[str]
    scheduled_nodes: Optional[str]
    selinux_context: Optional[str]
    shared: Optional[list[str]]
    sockets_per_board: Optional[int]
    sockets_per_node: Optional[Uint16NoValStruct]
    start_time: Optional[Uint64NoValStruct]
    state_description: Optional[str]
    state_reason: Optional[str]
    standard_error: Optional[str]
    standard_input: Optional[str]
    standard_output: Optional[str]
    submit_time: Optional[Uint64NoValStruct]
    suspend_time: Optional[Uint64NoValStruct]
    system_comment: Optional[str]
    time_limit: Optional[Uint32NoValStruct]
    threads_per_core: Optional[Uint16NoValStruct]
    tres_bind: Optional[str]
    tres_freq: Optional[str]
    tres_per_job: Optional[str]
    tres_per_node: Optional[str]
    tres_per_socket: Optional[str]
    tres_per_task: Optional[str]
    tres_req_str: Optional[str]
    user_id: Optional[int]
    user_name: Optional[str]
    maximum_switch_wait_time: Optional[int]
    wckey: Optional[str]
    current_working_directory: Optional[str]
