"""https://slurm.schedmd.com/rest_api.html#v0.0.42_job_desc_msg"""

from typing import Any, Optional

from pydantic import BaseModel

from .cron_entry import CronEntry
from .job_desc_msg_rlimits import JobDescMsgRlimits
from .uint16_no_val_struct import Uint16NoValStruct
from .uint32_no_val_struct import Uint32NoValStruct
from .uint64_no_val_struct import Uint64NoValStruct


class JobDescMsg(BaseModel):
    """v0.0.42 JobDescMsg"""

    account: Optional[str]
    account_gather_frequency: Optional[str]
    admin_comment: Optional[str]
    allocation_node_list: Optional[str]
    allocation_node_port: Optional[str]
    argv: Optional[list[str]]
    array: Optional[str]
    batch_features: Optional[str]
    begin_time: Optional[Uint64NoValStruct]
    flags: Optional[list[str]]
    burst_buffer: Optional[str]
    clusters: Optional[str]
    cluster_constraint: Optional[str]
    comment: Optional[str]
    contiguous: Optional[bool]
    container: Optional[str]
    container_id: Optional[str]
    core_specification: Optional[int]
    thread_specification: Optional[int]
    cpu_binding: Optional[str]
    cpu_binding_flags: Optional[list[str]]
    cpu_frequency: Optional[str]
    cpu_per_tres: Optional[str]
    crontab: Optional[CronEntry]
    deadline: Optional[int]
    delay_boot: Optional[int]
    dependency: Optional[str]
    end_time: Optional[int]
    environment: Optional[list[str]]
    rlimit: Optional[JobDescMsgRlimits]
    excluded_nodes: Optional[str]
    extra: Optional[str]
    constraints: Optional[str]
    group_id: Optional[str]
    hetjob_group: Optional[str]
    immediate: Optional[bool]
    job_id: Optional[int]
    kill_on_node_fail: Optional[bool]
    licenses: Optional[str]
    mail_type: Optional[list[str]]
    mail_user: Optional[str]
    mcs_label: Optional[str]
    memory_binding: Optional[str]
    memory_binding_type: Optional[list[str]]
    memory_pre_tres: Optional[str]
    name: Optional[str]
    network: Optional[str]
    nice: Optional[int]
    tasks: Optional[int]
    oom_kill_step: Optional[int]
    open_mode: Optional[list[str]]
    reserve_ports: Optional[int]
    overcommit: Optional[bool]
    partition: Optional[str]
    distribution_plane_size: Optional[Uint16NoValStruct]
    power_flags: Optional[list[Any]]
    prefer: Optional[str]
    hold: Optional[bool]
    priority: Optional[Uint32NoValStruct]
    profile: Optional[list[str]]
    qos: Optional[str]
    reboot: Optional[bool]
    required_nodes: Optional[list[str]]
    requeue: Optional[bool]
    reservation: Optional[str]
    script: Optional[str]
    shared: Optional[list[str]]
    site_factor: Optional[int]
    spank_environment: Optional[list[str]]
    distribution: Optional[str]
    time_limit: Optional[Uint32NoValStruct]
    time_minimum: Optional[Uint32NoValStruct]
    tres_bind: Optional[str]
    tres_per_job: Optional[str]
    tres_per_node: Optional[str]
    tres_per_socket: Optional[str]
    tres_per_task: Optional[str]
    user_id: Optional[str]
    wait_all_nodes: Optional[bool]
    kill_warning_flags: Optional[list[str]]
    kill_warning_signal: Optional[str]
    kill_warning_delay: Optional[Uint16NoValStruct]
    current_working_directory: Optional[str]
    cpus_per_task: Optional[int]
    minimum_cpus: Optional[int]
    maximum_cpus: Optional[int]
    nodes: Optional[str]
    minimum_nodes: Optional[int]
    maximum_nodes: Optional[int]
    minimum_boards_per_node: Optional[int]
    maximum_boards_per_node: Optional[int]
    minimum_sockets_per_board: Optional[int]
    sockers_per_node: Optional[int]
    threads_per_core: Optional[int]
    tasks_per_node: Optional[int]
    tasks_per_socket: Optional[int]
    tasks_per_core: Optional[int]
    tasks_per_board: Optional[int]
    ntasks_per_tres: Optional[int]
    minimum_cpus_per_node: Optional[int]
    memory_per_cpu: Optional[Uint64NoValStruct]
    memory_per_node: Optional[Uint64NoValStruct]
    temporary_disk_per_node: Optional[int]
    selinux_context: Optional[str]
    required_switches: Optional[Uint32NoValStruct]
    segment_size: Optional[Uint16NoValStruct]
    standard_error: Optional[str]
    standard_input: Optional[str]
    standard_output: Optional[str]
    wait_for_switch: Optional[int]
    wckey: Optional[str]
    x11: Optional[list[str]]
    x11_magic_cookier: Optional[str]
    x11_target_host: Optional[str]
    x11_target_port: Optional[int]
