"""Wrap jobs in variable contexts.

A user may wish to declare some variables locally for a few common jobs.
"""

import logging
import random
import string
import tempfile
from collections.abc import Callable, Mapping
from typing import TYPE_CHECKING, Any, Final, Literal

from pydantic import BaseModel, ConfigDict, DirectoryPath, model_validator

from pyantz.infrastructure.config import (
    JobConfig,
    JobPipeline,
    JobWithContext,
    add_parameters,
    no_submit_fn,
)
from pyantz.infrastructure.runner.job_manager import (
    JobVariables,
    run_job_no_parent_wrapper,
)

if TYPE_CHECKING:
    from pyantz.infrastructure.config import SubmissionFnType


class SetVariables(BaseModel):
    """Parmeters for running a job which sets variables."""

    model_config = ConfigDict(frozen=True)

    # job which will edit the variable context
    setter_job: Callable[..., Any]

    # Kwargs to pass to the setter job
    set_job_kwargs: Mapping[str, Any]

    # jobs to submit with the context of the setter job
    jobs: JobPipeline

@add_parameters(SetVariables)
@no_submit_fn
def set_variables(params: SetVariables) -> bool:
    """Set the variables for subsequent defined jobs.

    The `setter_job` is a slightly abnormal job. One of the parameters it accepts
    shall be `set_variable`, which is a closure that will set the enclosing variables.
    """
    logger = logging.getLogger(__name__)
    new_variables: dict[str, Any] = {}

    def set_var(key: str, value: Any) -> None:  # noqa: ANN401
        nonlocal new_variables
        new_variables[key] = value

    try:
        params.setter_job(
            set_var=set_var,
            **params.set_job_kwargs,
        )
    except Exception as exc:
        logger.exception("Unknown error in external set variable job.", exc_info=exc)
        return False
    else:
        return True


class VariableContextParams(BaseModel):
    """Parameters for running jobs sequentially within this job without submitting."""

    model_config = ConfigDict(frozen=True)

    # Jobs to submit with the new variables
    jobs: JobPipeline

    # variables to add to jobs when submitted
    shared_variables: Mapping[str, Any]


@add_parameters(VariableContextParams)
def run_jobs_in_context(
    params: VariableContextParams,
    submit_fn: SubmissionFnType,
) -> bool:
    """Submit the set of jobs with the shared variables. Not really anything fancy."""
    print("Submitting child job in context")
    for job in params.jobs:
        # add context
        updated_job = JobWithContext.from_config(job).inherit_context(
            params.shared_variables
        )
        submit_fn(updated_job)

    return True


class TemporaryDirectoryParams(BaseModel):
    """Params for providing a set of jobs a temporary directory."""

    model_config = ConfigDict(frozen=True)

    # jobs to run
    jobs: JobPipeline

    # used when placing the path to the temporary directory in variables
    variable_name: str

    # if set to local, will run these jobs in a simple pipeline
    # if set to remote, will submit these jobs.
    # if using remote, the user must provide a SHARED NON-TEMPORARY location in which to
    # place the temporary directory; obviously tempfile will terminate with this job
    submit_type: Literal["local", "remote"] = "local"

    # if using remote, MUST use this variable
    # if using local, this will override the default usage of tempdir
    shared_working_dir: DirectoryPath

    @model_validator(mode="after")
    def validate_submit_and_dir(self) -> TemporaryDirectoryParams:
        """Validate that a user submitting remotely has set the shared working dir."""
        if self.submit_type == "remote" and not self.shared_working_dir.exists():
            raise ValueError
        return self


@add_parameters(TemporaryDirectoryParams)
def run_jobs_with_temp_dir(
    params: TemporaryDirectoryParams, submit_fn: SubmissionFnType
) -> bool:
    """Run jobs with a temporary directory."""
    if params.submit_type == "local":
        return _run_jobs_temp_dir_local(params, submit_fn=submit_fn)

    return _run_jobs_temp_dir_remote(params, submit_fn)


def _run_jobs_temp_dir_remote(
    params: TemporaryDirectoryParams, submit_fn: SubmissionFnType
) -> bool:
    """Submit the jobs to be run after creating a working dir for them."""
    dir_name_length = random.randint(5, 20)  # noqa: S311
    dir_name = f"tempdir_{_generate_random_string(dir_name_length)}"
    dir_path = params.shared_working_dir / dir_name

    # create the working directory in a separate job
    mkdir_job = JobConfig(
        name="__autogenerate_mkdir__",
        function="pyantz.jobs.files.simple.mkdir",  # type: ignore[arg-type]  # ty:ignore[invalid-argument-type]
        parameters={"dir_path": dir_path},
    )

    # and we have to delete it
    delete_dir_job = JobConfig(
        name="__autogenerated_clean_up_dir__",
        # should only happen after everything else has completed!
        depends_on={job.job_id for job in (*params.jobs, mkdir_job)},
        function="pyantz.jobs.files.simple.delete",  # type: ignore[arg-type] # ty:ignore[invalid-argument-type]
        parameters={"path": dir_path},
    )

    # mkdir must happen first so make everything depend on mkdir
    jobs = [
        job.model_copy(
            update={"depends_on": {*(job.depends_on or ()), mkdir_job.job_id}}
        )
        for job in params.jobs
    ]
    # notional order, but with the dependencies may not fully matter
    jobs = [mkdir_job, *jobs, delete_dir_job]

    for job in jobs:
        submit_fn(job)

    return True


def _run_jobs_temp_dir_local(
    params: TemporaryDirectoryParams, submit_fn: SubmissionFnType
) -> bool:
    """Run the jobs locally with a temporary directory."""
    curr_variables: Final[Mapping[str, Any]] = (
        _vars if (_vars := JobVariables.get()) else {}
    )

    with tempfile.TemporaryDirectory() as tmpdirname:
        variables_with_dir: Final[Mapping[str, Any]] = {
            **curr_variables,
            params.variable_name: tmpdirname,
        }
        success = True
        for job in params.jobs:
            job_with_parent_context = JobWithContext.from_config(job).inherit_context(
                variables_with_dir
            )
            if not run_job_no_parent_wrapper(job_with_parent_context, submit_fn):
                success = False
                break

    return success


def _generate_random_string(length: int) -> str:
    """Generate a semirandom string for the directory names."""
    # NOTE: AI SLOP BELOW
    # Combine lowercase letters, uppercase letters, and digits
    characters = string.ascii_letters
    # Use random.choices to select 'k' characters with replacement
    return "".join(random.choices(characters, k=length))  # noqa: S311
